swagger: Script the OpenAPI spec update
elastic/cloud-sdk-go pull request #342
Opened 2021-08-16 12:22 UTC by marclop

## Description

Adds a new script that updates the OpenAPI spec with the milestone of
the ECE release.

2021-08-19 09:29 UTC, marclop commented
The documentation changes have been done in a separate PR: https://github.com/elastic/cloud-sdk-go/pull/349

2021-08-19 15:40 UTC, obierlaire requested changes

2021-08-19 15:40 UTC, obierlaire commented on Makefile
> +export ECE_BRANCH ?= 62
Why not keeping the `ms-` prefix? Looks like you are adding back the `ms-` prefix in `scripts/update-swagger.sh`

2021-08-20 09:33 UTC, obierlaire approved these changes

2021-08-20 12:23 UTC, merged